image: Visual Studio 2019

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

before_build:
- choco install dotnetcore-sdk
- nuget restore ".\src\Downloader.sln"
- choco install opencover.portable
- choco install codecov

build:
  project: .\src\Downloader.sln
  verbosity: minimal
  
test_script:  
  - OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:test ".\src\Downloader.Test\Downloader.Test.csproj" -filter:"+[*]* -[Downloader.Test.*]* -[Downloader.Sample.*]*" -output:".\downloader_coverage.xml" -oldstyle
  - codecov -f "downloader_coverage.xml"
