image: Visual Studio 2019

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

before_build:
- choco install dotnetcore-sdk
- choco install opencover.portable
- choco install codecov
- cd src
- nuget restore Downloader.sln

build:
  project: Downloader.sln
  verbosity: minimal
  
test_script:
  - OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:test -filter:"+[*]* -[Downloader.Test.*]* -[Downloader.Sample.*]*" -output:".\downloader_coverage.xml" -oldstyle
  - codecov -f "downloader_coverage.xml"
