image: Visual Studio 2019

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

before_build:
- nuget restore ".\src\Downloader.sln"
- choco install opencover.portable
- choco install codecov

build:
  project: .\src\Downloader.sln
  verbosity: minimal
  
test_script:
  - dotnet test ".\src\Downloader.Test\Downloader.Test.csproj" --configuration Debug--no-build
  - OpenCover.Console.exe -register:bezzad -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:".\src\Downloader.Test\bin\Debug\net5\Downloader.Test.dll -noshadow" -filter:"+[Downloader*]* -[Downloader.Test*]*" -output:".\downloader_coverage.xml"
  - codecov -f "downloader_coverage.xml"
