version: '2.0.2.{build}'
image: Visual Studio 2019
skip_tags: true

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

codecov:
  token: b9beada8-a4af-4ffb-928f-1f1268f6259d

before_build:
- nuget restore .\src\
- choco install opencover.portable
- choco install codecov

build:
  project: .\src\Downloader.sln
  verbosity: minimal

test_script: 
  - OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:test -filter:"+[UnitTestTargetProject*]* -[Downloader.Test*]*" -output:".\downloader_coverage.xml" -oldstyle
  - codecov -f "Downloader_coverage.xml
