version: '3.8'

# NOTE: do not execute both win and linux services, because both of them are using port 3333
services:

  #windows-net6:
  #  image: mcr.microsoft.com/windows/servercore:ltsc2022
  #  build: 
  #    context: .
  #    dockerfile: ./dockerfile
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #  volumes: 
  #    - .:/app
  #  working_dir: /app
  #  container_name: downloader-win

  linux-net6:
    image: mcr.microsoft.com/dotnet/sdk:7.0
    build: 
      context: .
      dockerfile: ./dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes: 
      - .:/app
    working_dir: /app
    container_name: downloader-linux
    