name: Windows x64

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore ./src/Downloader.sln
    - name: Build
      run: dotnet build ./src/Downloader.sln --no-restore
    - name: Test
      run: dotnet test ./src/Downloader.sln --no-build --verbosity normal